import { Stars } from './stars-model';
import { Cidade } from './cidade-model';
import { Estado } from './estado-model';
import { Avaliacoes } from './avaliacoes-model';
import { Experiencias } from './experiencias-model';
export class Usuario {
    idUsuario: number;
    nome: string;
    login: string;
    senha: string;
    email: string;
    urlFacebook: string;
    hasWhatsapp: string;
    telefone: string;
    profissao: string;
    endereco: string;
    complemento: string;
    cidade: Cidade = new Cidade();
    estado: Estado = new Estado();
    cep: string;
    sexo: string;
    sobrenome: string;
    avaliacao: Avaliacoes = new Avaliacoes(0,0);
    idFuncionario: number;
    residencia: string;
    cpf_cnpj: string;
    idRole: number;
    mediaAvaliacao:number;
    experiencia:Experiencias =new Experiencias();
    stars:Stars = new Stars();
}